### ISSUE TITLE
tutorial9_complete.py misses content

### ISSUE THREAD

**Issue by matthiaskoenig** [kerimoyle/libcellml-tutorials#12]
The `tutorial9_complete.py` is empty. No solution there.

**Comment by kerimoyle** [comment]
The tutorials for today were the ones inside the `combine2020` folder.  The others are well out of date, so not for consumption ... That's why it's better to access them through the readthedocs link rather than here.  That way you should only see the ones that are relevant and ready.

**Comment by matthiaskoenig** [comment]
Sorry by bet. Just close the issues. Perhaps it makes sense to remove the old tutorial from the repo.
