### ISSUE TITLE
Small issue with the CMake command in step 2.a

### ISSUE THREAD

**Issue by agarny** [kerimoyle/libcellml-tutorials#13]
Step 2.a should read `cmake -DINSTALL_PREFIX=../install ../source`, not `cmake -DINSTALL_PREFIX=../install ../source .`.

**Comment by kerimoyle** [comment]
I know it's redundant, but I like the extra argument to remind me what I'm doing.  Perhaps I should specify all of the options and flags the first time around (with the -S and -B etc tags too).  I'll add something which explains what the arguments are doing.

**Comment by agarny** [comment]
I would just drop that final `.`. I have never seen CMake-related instructions that do that and it caught me off guards.

**Comment by kerimoyle** [comment]
Haha, fair enough.  I've never seen them without it! :D I've updated the instructions to include the variations and people can do what they want :)
